#!/bin/sh -e
set -x

# For a specified service, load its service config.json file into env variables.
# Intended to simplify access/use of our service vars in scripts.
# Usage: service-json2env /path/to/config.json

service_settings_load() {
  local tmp_settings; tmp_settings=$1
  SERVICE_NAME=$(cat $tmp_settings | jq -c '.services | keys[]')
  SERVICE_STATE=$(cat $tmp_settings | jq -c '.services[].state')
  SERVICE_ENABLE=$(cat $tmp_settings | jq -c '.services[].enable')
  SERVICE_DISABLE=$(cat $tmp_settings | jq -c '.services[].disable')
  SERVICE_RUN=$(cat $tmp_settings | jq -c '.services[].run')
  SERVICE_CHECK=$(cat $tmp_settings | jq -c '.services[].check')
  SERVICE_FINISH=$(cat $tmp_settings | jq -c '.services[].finish')
  SERVICE_LOG=$(cat $tmp_settings | jq -c '.services[].log')
  SERVICE_TAGS=$(cat $tmp_settings | jq -c '.services[].tags[]')
  SERVICE_INPUT=$(cat $tmp_settings | jq -c '.services[].input[]')
  SERVICE_OUTPUT=$(cat $tmp_settings | jq -c '.services[].output[]')

  return 0
}

main () {
  service_settings_load "$@"
}

main "$@"
