describe("A context", function()
  before(function() end)
  after(function() end)
  context("A nested context", function()
    it("A test", function()
      assert_not_equal("ham", "cheese")
    end)
    context("Another nested context", function()
      it("Another test", function()
        assert_greater_than(2, 1)
      end)
    end)
  end)
  it("A test in the top-level context", function()
    assert_equal(3, 3)
  end)
end)
