#!/usr/bin/env sh

SOURCE=$0
TMP_SERVICE=$(basename $(dirname $(dirname $SOURCE)))

echo "Configuring $TMP_SERVICE"
socklog-conf notify log adm

#get ip of eth0

# now make mods to the files...
cat > /etc/sv/$TMP_SERVICE/log/run << "EOF"
#!/bin/sh
SERVICE_NAME=$(basename $(dirname $(pwd)))

exec chpst -u root logger -t $SERVICE_NAME -p local0.notice
EOF

cat > /etc/sv/$TMP_SERVICE/run << "EOF"
#!/bin/sh -e
  BRIDGE_ADDRESS=$(ip -o -4 address show eth0 | awk '{ print $4}' | cut -d '/' -f 1)
  LOGGER_PORT_REMOTE=10514
  PIPE=/var/log/socklog/.notify
  if [ ! -p "$PIPE" ]; then mkfifo -m0620 "$PIPE"; chown log:adm "$PIPE"; fi
  exec <> "$PIPE"
  exec chpst -u log uncat -s49999 -t90 | logger -n $ETH0_ADDRESS -u /dev/null -t foobar-server -p local0.notice 
#  \
#  	!tryto -pv nc $ETH0_ADDRESS $LOGGER_PORT_REMOTE
EOF

# | logger -n $ETH0_ADDRESS -u /dev/null -t foobar-server -p local0.notice
echo "Enabling $TMP_SERVICE"
chmod ug+x /etc/sv/$TMP_SERVICE/run
chmod ug+x /etc/sv/$TMP_SERVICE/log/run
[ ! -e /etc/service/$TMP_SERVICE ] && ln -s /etc/sv/$TMP_SERVICE /etc/service/
ln -sf /usr/bin/sv /etc/init.d/$TMP_SERVICE

