#!/bin/sh

#
# Package install function wrapper
# @see core/airstack-helpers
#


. /package/airstack/core/airstack-helpers
ERROR_MESSAGE_DEFAULT="[ERROR] core-package-install"

main() {
  pkg_install "$@"
  error_check "package installation"
}

main "$@"
