#!/usr/bin/env sh

SOURCE=$0
TMP_SERVICE=$(basename $(dirname $(dirname $SOURCE)))

echo "Configuring $TMP_SERVICE"
socklog-conf unix nobody log

# mods to config files
cat > /etc/sv/$TMP_SERVICE/log/main/main/config << "EOF"
s999999
n11
EOF

echo "Enabling $TMP_SERVICE"
[ ! -e /etc/service/$TMP_SERVICE ] && ln -s /etc/sv/$TMP_SERVICE /etc/service/
