#!/bin/sh

socklog_config_create() {
  set -e
  local i; i=$1
  local tmp_ip=$(cat "$i"_IP)
  local tmp_port=$(cat "$i"_PORT)

  local tmp_dir; tmp_dir=/etc/sv/socklog-unix/log/main/toremote/$tmp_ip:$tmp_port
  [ -d $tmp_dir ] || mkdir -p $tmp_dir

  # create config file
  local tmp_configfile; tmp_configfile=$tmp_dir/config
  > $tmp_configfile

  # handle multiple patterns
  local tmp_pattern;local x;
  for x in $(ls "$i"_PATTERN_* | sort -n); do
    tmp_pattern=$(cat "$x")
    echo $tmp_pattern >> $tmp_configfile
  done
  echo "s2000" >> $tmp_configfile
  echo "n10" >> $tmp_configfile
  echo "N5" >> $tmp_configfile
  echo "t2" >> $tmp_configfile
  echo p"$(hostname) " >> $tmp_configfile
  echo "!tryto -pv -k 2 -n 5 nc -q0 $tmp_ip $tmp_port" >> $tmp_configfile
  chmod 0644 $tmp_configfile

  # set permissions
  find /etc/sv/socklog-unix/log/main/toremote/ -type d -exec chown log:nogroup {} +
  find /etc/sv/socklog-unix/log/main/toremote/ -type d -exec chmod 750 {} +
  set +e
}


socklog_defaults_create() {
  set -e
  [ -d /etc/sv/socklog-unix/log/ ] || mkdir -p /etc/sv/socklog-unix/log/
  cd /etc/sv/socklog-unix/log

  mkdir -p main/auth
  printf "s999999\nn5\n-*\n+auth.*\n+authpriv.*" > main/auth/config
  mkdir -p main/cron
  printf "s999999\nn5\n-*\n+cron.*" > main/cron/config
  mkdir -p main/daemon
  printf "s999999\nn5\n-*\n+daemon.*" > main/daemon/config
  mkdir -p main/debug
  printf "s999999\nn5\n-*\n+*.debug*" > main/debug/config
  mkdir -p main/ftp
  printf "s999999\nn5\n-*\n+ftp.*" > main/ftp/config
  mkdir -p main/kern
  printf "s999999\nn5\n-*\n+kern.*" > main/kern/config
  mkdir -p main/local
  printf "s999999\nn5\n-*\n+local.*" > main/local/config
  mkdir -p main/mail
  printf "s999999\nn5\n-*\n+mail.*" > main/mail/config
  mkdir -p main/main
  printf "s999999\nn10" > main/main/config
  mkdir -p main/news
  printf "s999999\nn5\n-*\n+news.*" > main/news/config
  mkdir -p main/syslog
  printf "s999999\nn5\n-*\n+syslog.*" > main/syslog/config
  mkdir -p main/user
  printf "s999999\nn5\n-*\n+user.*" > main/user/config
  find ./main/* -name config -exec chmod 0644 {} +

  find ./main/* -type d -exec chown log:nogroup {} +
  find ./main/* -type d -exec chmod 750 {} +
  set +e
}


socklog_facilities_create() {
  set -e
  local tmp_facilities; tmp_facilities="$@"

  local tmp_file; tmp_file=/etc/sv/socklog-unix/log/run
  echo '#!/bin/sh' > $tmp_file
  echo "exec chpst -ulog svlogd -tt -b 10000 -l 1000 $tmp_facilities" >> $tmp_file

  chmod ug+x $tmp_file
  set +e
}


main() {
  set -e
  socklog_defaults_create

  [ -f /var/log/socklog ] || ln -sf /service/socklog-unix/log/main /var/log/socklog
  [ -f /var/log/syslog ] || ln -sf /var/log/socklog/main/current /var/log/syslog

  local i; local default_facilities;
  default_facilities="main/main main/auth main/cron main/daemon main/debug \
  main/ftp main/kern main/local main/mail main/news main/syslog main/user"

  for i in $(ls /env/IPLOG_? | sort -n); do
    socklog_config_create $i
  done

  local tmp_dirs;
  for i in $(ls /etc/sv/socklog-unix/log/main/toremote/ | sort -n); do
    tmp_dirs="$tmp_dirs main/toremote/$i"
  done
  socklog_facilities_create "$default_facilities $tmp_dirs"
  set +e
}


main "$@"
