#!/bin/sh -e

SOURCE=$0
TMP_SERVICE=$(basename $(dirname $SOURCE))

## end common head

echo "Configuring $TMP_SERVICE"
# configure if not already done
[ ! -e /etc/sv/$TMP_SERVICE/log ] && socklog-conf unix nobody log

# TODO investigate update-service util
# if update-service --list socklog-unix >/dev/null || true; then
# 	socklog-conf unix nobody log
# 	update-service --add /etc/sv/socklog-unix
# fi

# mods to config files
cat > /etc/sv/$TMP_SERVICE/log/main/main/config << "EOF"
s999999
n11
EOF

# cat > /etc/sv/$TMP_SERVICE/check << "EOF"
# TODO: works to check here, but inefficient time-wise so not a great healthcheck... 
# move to runit service check 
# LOGFILES="/var/log/socklog/main/current"
# while [ ! -f "$LOGFILES" ]; do sleep 0.1 && printf "."; done; printf "\n"
# msg "$(sv status /service/*)\n"
# EOF

TMP_RUNLEVELS="single multi"

## common footer start

echo "Enabling $TMP_SERVICE"
[ -e /etc/sv/$TMP_SERVICE/run ] && chmod ug+x /etc/sv/$TMP_SERVICE/run
[ -e /etc/sv/$TMP_SERVICE/log/run ] && chmod ug+x /etc/sv/$TMP_SERVICE/log/run

for i in ${TMP_RUNLEVELS:-multi}; do
	[ ! -e /etc/runit/runsvdir/$i/$TMP_SERVICE ] && ln -s /etc/sv/$TMP_SERVICE /etc/runit/runsvdir/$i
done

# symlink current log to syslog
ln -s /var/log/socklog/main/current /var/log/syslog

# adding to init.d for service command compatibility
ln -sf /usr/bin/sv /etc/init.d/$TMP_SERVICE
