#!/bin/sh -e

SOURCE=$0
TMP_SERVICE=$(basename $(dirname $SOURCE))

## end common head

echo "Configuring $TMP_SERVICE"
# mkdir -vp /var/run/sshd
# sed -i -e 's/session    required     pam_loginuid.so/#session    required     pam_loginuid.so/' /etc/pam.d/sshd

printf "\tsetting ssh password\n"
echo "$AIRSTACK_USER_NAME:$AIRSTACK_USER_PASSWORD" | chpasswd


## runit files

printf "\tcreating runit directories\n"
mkdir -p /etc/sv/$TMP_SERVICE/log

printf "\tcreating runit service file\n"
cat > /etc/sv/$TMP_SERVICE/run << "EOF"
#!/bin/sh
SERVICE_NAME=$(basename $(pwd))

# sv -w2 check socklog-unix >/dev/null || exit 1
exec 2>&1

exec chpst -u root /usr/sbin/dropbear -F -E -R
EOF

printf "\tcreating runit log file\n"
cat > /etc/sv/$TMP_SERVICE/log/run << "EOF"
#!/bin/sh
SERVICE_NAME=$(basename $(dirname $(pwd)))

exec chpst -u root logger -t $SERVICE_NAME -p local0.notice
EOF

## common footer start

echo "Enabling $TMP_SERVICE"
[ -e /etc/sv/$TMP_SERVICE/run ] && chmod ug+x /etc/sv/$TMP_SERVICE/run
[ -e /etc/sv/$TMP_SERVICE/log/run ] && chmod ug+x /etc/sv/$TMP_SERVICE/log/run

for i in ${TMP_RUNLEVELS:-multi}; do
	[ ! -e /etc/runit/runsvdir/$i/$TMP_SERVICE ] && ln -s /etc/sv/$TMP_SERVICE /etc/runit/runsvdir/$i
done

# adding to init.d for service command compatibility
ln -sf /usr/bin/sv /etc/init.d/$TMP_SERVICE
