#!/usr/bin/env sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

msg() {
    # bold
    printf "\033[1m=> $@\033[m"
}

msg_ok() {
    # bold/green
    printf "\033[1m\033[32m OK\033[m\n"
}

msg_fail() {
    # bold/red
    printf "\033[1m\033[31m FAIL\033[m\n"
}

msg_warn() {
    # bold/yellow
    printf "\033[1m\033[33mWARNING: $@\033[m"
}

## END COMMON HEAD

msg "Initializing Runit Level 2\n"

# Enable all services in parallel. See [TODO service docs] for details.
echo $(for i in $AIRSTACK_SERVICES; do echo /etc/airstack/$i/runit/enable; done) | xargs -n1 sh

# load files in /etc/rc.local
[ -x /etc/rc.local ] && exec /etc/rc.local
