#!/bin/sh

## STATUS: WIP! Not fully refactored yet to use new config.json.
# TODO: refactor similar to socklog-remote/enable

set -e

ln -sf /package/airstack/haproxy/haproxy.cfg /etc/haproxy/


echo -n "Generating ssl cert for haproxy "
	mkdir -p /etc/ssl && \
	export PASSPHRASE=$(head -c 500 /dev/urandom | tr -dc a-z0-9A-Z | head -c 128; echo) && \
	openssl genrsa -des3 -out server.key -passout env:PASSPHRASE 2048 && \
	openssl req -new -batch -key server.key -out server.csr -subj "/C=/ST=/O=org/localityName=/commonName=org/organizationalUnitName=org/emailAddress=/" -passin env:PASSPHRASE && \
	openssl rsa -in server.key -out server.key -passin env:PASSPHRASE && \
	openssl x509 -req -days 3650 -in server.csr -signkey server.key -out server.crt && \
	cat server.crt server.key > /etc/ssl/server.pem
	echo "[OK]"

if [ -z "$HAPROXY_USERNAME" ]; then
    export HAPROXY_USERNAME="admin"
fi

if [ -z "$HAPROXY_URI" ]; then
    export HAPROXY_URI="/haproxy?stats"
fi

if [ -n "$HAPROXY_PASSWORD" ]
then
  echo "	stats enable" >> /etc/haproxy/haproxy.cfg
  echo "	stats auth $HAPROXY_USERNAME:$HAPROXY_PASSWORD" >> /etc/haproxy/haproxy.cfg
  echo "	stats uri $HAPROXY_URI" >> /etc/haproxy/haproxy.cfg
fi
