#!/usr/bin/env sh

SOURCE=$0
TMP_SERVICE=$(basename $(dirname $(dirname $SOURCE)))

echo "Configuring $TMP_SERVICE"
socklog-conf klog nobody log

echo "Enabling $TMP_SERVICE"
[ ! -e /etc/service/$TMP_SERVICE ] && ln -s /etc/sv/$TMP_SERVICE /etc/service/
ln -sf /usr/bin/sv /etc/init.d/$TMP_SERVICE
