#!/bin/sh
#
# Airstack helper functions for airstack shell scripts.
#
# Usage:
#   # Set error_check prefix and load helpers if they exist
#   # Exit script if airstack-helpers cannot be sourced
#   ERROR_MESSAGE_DEFAULT="[ERROR] CHANGEME -"
#   [ -f "/package/airstack/core/airstack-helpers" ] && { . /package/airstack/core/airstack-helpers ;} || { printf "missing airstack-helpers. exiting.\n" && exit 113 ;}
#
# @see /docs/scripting.md for shell references and style guides
#


# TODO use shellcheck on build to ensure we aren't using bashisms.
# switch to mksh-static for dash
# http://lowendbox.com/blog/replacing-big-fat-bash-with-dash-for-scripting/
# http://rgeissert.blogspot.com/2012/03/bash-way-is-faster-but-only-with-bash.html


################################################################################
# LOAD EXTERNAL FUNCTIONS
################################################################################

# Make error_check available
. /command/core-error-check


################################################################################
# MESSAGE FUNCTIONS
################################################################################

msg() {
    # bold
    printf "\033[1m=> $@\033[m"
}

msg_ok() {
    # bold/green
    printf "\033[1m\033[32m OK\033[m\n"
}

msg_fail() {
    # bold/red
    printf "\033[1m\033[31m FAIL\033[m\n"
}

msg_warn() {
    # bold/yellow
    printf "\033[1m\033[33mWARNING: $@\033[m"
}
