#!/bin/sh -e
set -x

# Load the core config.json file into env variables.
# Intended to simplify access/use of our core vars in scripts.
# Env var files are created in /etc/airstack/env
# Usage: json2env-core

load_vars() {
  local runtime; runtime=$(cat /etc/airstack/runtime.json)
  mkdir -p /etc/airstack/env
  cd /etc/airstack/env
  for key in $(echo $runtime | jq -r -c 'keys[]'); do
    [ "$key" = "services" ] && continue
    /package/airstack/core/json2env ".\"$key\""
  done
}

load_vars
