#!/bin/sh
set -e
#set -x

# Purpose: given a service json file, return a list of the tags for a specific service
# Usage: $1 is the service settings.
# example usage is:
# service-tags /package/airstack/dropbear/config.json
# TODO: if the json has any missing options, it will assume defaults.

init() {
  BASEDIR="/etc/sv"
  SERVICE_SETTINGS=$1
  [ -z "$SERVICE_SETTINGS" ] && (echo 'all params not set.' && exit 1)
  return 0
}

main_settings_load() {
  local tmp_settings
  tmp_settings=$SERVICE_SETTINGS
  AIRSTACK_TAGS=$(cat $tmp_settings | jq -r '.services[].input[].tags[]')
}

main() {
  init "$@"
  main_settings_load
  echo $AIRSTACK_TAGS
}

main "$@"
