#!/bin/sh -e

service_install() {
  DEBIAN_FRONTEND=noninteractive
  apt-get update;
  apt-get install -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold --no-install-recommends --no-install-suggests -y "$@"
}

main() {
  service_install "$@"
}

main "$@"
