#!/bin/sh -e

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

msg() {
    # bold
    printf "\033[1m=> $@\033[m"
}

msg_ok() {
    # bold/green
    printf "\033[1m\033[32m OK\033[m\n"
}

msg_fail() {
    # bold/red
    printf "\033[1m\033[31m FAIL\033[m\n"
}

msg_warn() {
    # bold/yellow
    printf "\033[1m\033[33mWARNING: $@\033[m"
}

## END COMMON HEAD

msg "Initializing Runit Level 1\n"

# runlevel to initialize vms and physical machines...

# Log the system boot.
dmesg >/var/log/dmesg.log

# Get stopit and reboot read for usage.
install -m0 /dev/null /etc/runit/reboot
install -m0 /dev/null /etc/runit/stopit

# load files in /etc/rc.local
[ -x /etc/rc.local ] && exec /etc/rc.local
