#!/bin/sh -e

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

msg() {
    # bold
    printf "\033[1m=> $@\033[m"
}

msg_ok() {
    # bold/green
    printf "\033[1m\033[32m OK\033[m\n"
}

msg_fail() {
    # bold/red
    printf "\033[1m\033[31m FAIL\033[m\n"
}

msg_warn() {
    # bold/yellow
    printf "\033[1m\033[33mWARNING: $@\033[m"
}

## END COMMON HEAD

msg "Initializing Runit Level 2\n"

msg "Starting /dev/log service\n"
/etc/airstack/socklog-unix/enable 2>&1 && msg_ok

runsvchdir single >/dev/null

# run in bg
env - PATH=$PATH \
/usr/bin/runsvdir -P /etc/service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................' &

# wait until socklog is up b4 proceeding
# TODO put in healthcheck in check script instead of default
while sv check socklog-unix >/dev/null && false; do
sv up socklog-unix >/dev/null
done

LOGFILES="/var/log/socklog/main/current"
while [ ! -f "$LOGFILES" ]; do sleep 0.1 && printf "."; done; printf "\n"
msg "$(sv status /service/*)\n"

# switch to multi runlevel
runsvchdir multi >/dev/null

# Enable all services in parallel. See [TODO service docs] for details.
# TODO error check to ensure that service has enable script b4 execution.
echo $(for i in $AIRSTACK_SERVICES; do echo /etc/airstack/$i/enable; done) | xargs -n1 sh

# load files in /etc/rc.local
[ -x /etc/rc.local ] && /etc/rc.local
