#!/usr/bin/env sh

SOURCE=$0
TMP_SERVICE=$(basename $(dirname $(dirname $SOURCE)))

echo "Configuring $TMP_SERVICE"
RUNIT_DIR="/etc/runit"
[ -e $RUNIT_DIR/runit ] || ln -s /etc/airstack/$TMP_SERVICE/config/runit $RUNIT_DIR
[ -L /etc/rc.local ] || (rm -f /etc/rc.local && ln -s /etc/airstack/$TMP_SERVICE/config/rc.local /etc/)

# enable init utils
INIT_DIR="/etc/airstack/$TMP_SERVICE/config/init"
for i in $(ls $INIT_DIR/); do
[ -e /usr/local/bin/$i ] || ln -s $INIT_DIR/$i /usr/local/bin/$i
done
