#!/bin/bash

# TODO: use /package/admin/airstack/conf/runtime.json instead of AIRSTACK_SERVICE_VARS
cat /etc/environment | grep AIRSTACK_SERVICE_VARS | cut -d '=' -f 2 > /package/admin/airstack/conf/airstack_service_vars.json

cat /package/admin/airstack/conf/airstack_service_vars.json

# cat /etc/environment | grep AIRSTACK_SERVICE_VARS
# export $(set -o posix ; set| grep AIRSTACK_TAGS_ROLE)

# eval $(cat /etc/environment | while read -r TMP;do grep AIRSTACK_SERVICE_VARS | awk '{print $1"=\047"$2"\047"}' FS='[=]'; done)
# export AIRSTACK_SERVICE_VARS

# echo $(cat /etc/environment | while read -r TMP;do grep AIRSTACK_SERVICE_VARS; done) > /package/admin/airstack/conf/services.json
# set -o posix ; set| grep "AIRSTACK_"


