#!/bin/bash

HANDLER_DIR="/etc/serf/handlers"
if [ "$SERF_EVENT" = "user" ]; then
	EVENT="user-$SERF_USER_EVENT"
elif [ "$SERF_EVENT" = "query" ]; then
	EVENT="query-$SERF_QUERY_NAME"
elif [[ "$SERF_EVENT" =~ member-.* ]]; then
	EVENT="$SERF_TAG_ROLE-member-event"
	# EVENT="$SERF_TAG_ROLE-$SERF_EVENT"
else
	EVENT=$SERF_EVENT
fi
HANDLER="$HANDLER_DIR/$EVENT"
[ -f "$HANDLER" -a -x "$HANDLER" ] && exec chpst -u root "$HANDLER" || :
