#!/bin/sh

# Linux From Scratch Runit Stage 1 Bootscript.
# Copyright 2014 James Powell, Keith Hedger, and Stoat of LinuxQuestions.
# Work derived from VoidLinux and ArchIgnite and adapted for LFS.

PATH=/bin:/sbin:/usr/bin:/usr/sbin

# This will setup a sulogin shell just in case any part of the boot process suddenly stops
# for whatever reason.
emergency_shell() {
    echo "Cannot continue due to errors above, starting emergency shell."
    echo "When ready type exit to continue booting."
    /bin/sh -l
}

msg() {
    # bold
    printf "\033[1m=> $@\033[m"
}

msg_ok() {
    # bold/green
    printf "\033[1m\033[32m OK\033[m\n"
}

msg_fail() {
    # bold/red
    printf "\033[1m\033[31m FAIL\033[m\n"
}

msg_warn() {
    # bold/yellow
    printf "\033[1m\033[33mWARNING: $@\033[m"
}

msg "Welcome to Airstack \n"

# By default Stage 1 should already come with the system defaults and recommended setups.
# If you need to load anything optional, you may use the /etc/runit.conf file as a method
# to load optional system preferences.
. /etc/runit.conf

# The LFS rc.site file contains parameters and system variables that can customize various
# aspects of the boot process. Source it now if it exists. Otherwise, defaults will be used.
[ -r /etc/sysconfig/rc.site ] && . /etc/sysconfig/rc.site

# A function from init-functions.
is_true()
{
   [ "$1" = "1" ] || [ "$1" = "yes" ] || [ "$1" = "true" ] ||
   [ "$1" = "y" ] || [ "$1" = "t" ]
}

# Log the system boot.
dmesg >/var/log/dmesg.log

# Get stopit and reboot read for usage.
install -m0 /dev/null /etc/runit/reboot
install -m0 /dev/null /etc/runit/stopit

msg "Initialization complete, running stage 2... \n"
sleep 3
