#!/bin/sh -e

######################################################################
# Common Head

SOURCE=$0
TMP_SERVICE=$(basename $(dirname $SOURCE))

# End Common Footer
######################################################################


# TODO: remove this script after implementing the run command in AIRSTACK_RUNTIME_VARS

# Main script
while true; do
	echo "HELLO $TMP_SERVICE"
	sleep 1
done



######################################################################
# Common Footer

echo "Enabling $TMP_SERVICE"
[ -e /etc/sv/$TMP_SERVICE/run ] && chmod ug+x /etc/sv/$TMP_SERVICE/run
[ -e /etc/sv/$TMP_SERVICE/log/run ] && chmod ug+x /etc/sv/$TMP_SERVICE/log/run

for i in ${TMP_RUNLEVELS:-multi}; do
  [ ! -e /etc/runit/runsvdir/$i/$TMP_SERVICE ] && ln -s /etc/sv/$TMP_SERVICE /etc/runit/runsvdir/$i
done

# adding to init.d for service command compatibility
ln -sf /usr/bin/sv /etc/init.d/$TMP_SERVICE
# default tail the syslog file

# End Common Footer
######################################################################
