################################################################################
# PACKAGES: DEVELOPMENT
#
# Add development packages here.
################################################################################

RUN set -e; \
  /command/core-package-install \
    vim-tiny ethtool bwm-ng man-db info psmisc net-tools less wget sudo procps inotify-tools; \
  ln -s /usr/bin/vim.tiny /usr/bin/vim
