#!/usr/bin/env sh

SOURCE=$0
TMP_SERVICE=$(basename $(dirname $(dirname $SOURCE)))

echo "Configuring $TMP_SERVICE"
mkdir -vp /var/run/sshd
sed -i -e 's/session    required     pam_loginuid.so/#session    required     pam_loginuid.so/' /etc/pam.d/sshd
echo "$AIRSTACK_USER_NAME:$AIRSTACK_USER_PASSWORD" | chpasswd

printf "\tcreating runit directories\n"
mkdir -vp /etc/sv/$TMP_SERVICE/log

printf "\tcreating runit service file\n"
cat - > /etc/sv/$TMP_SERVICE/run <<END
#!/bin/sh
SERVICE_NAME=$(basename $(pwd))

#dependencies
# sv check socklog-unix >/dev/null || exit 1
exec 2>&1

#command
exec chpst -u root /usr/sbin/sshd -D -e
END

printf "\tcreating runit log file\n"
cat - > /etc/sv/$TMP_SERVICE/log/run <<END
#!/bin/sh
SERVICE_NAME=$(basename $(dirname $(pwd)))

exec chpst -u root logger -t $SERVICE_NAME -p local0.notice
END

echo "Enabling $TMP_SERVICE"
chmod ug+x /etc/sv/$TMP_SERVICE/run
chmod ug+x /etc/sv/$TMP_SERVICE/log/run
[ ! -f /etc/service/$TMP_SERVICE ] && ln -s /etc/sv/$TMP_SERVICE /etc/service/
